### PR TITLE
add hello before program

### PR DESCRIPTION
**Pull request by chatmethar-comp**
hello user before run program for friendly

### CODE REVIEW

**Comment by omaiwamoshinderu** [comment]
Approve

**Review by ProjecTz20 — APPROVED** [review]
nice

**Review by ProjecTz20 — CHANGES_REQUESTED** [review]
add hello project

**Comment by omaiwamoshinderu** [comment]
LGBT+

**Review by omaiwamoshinderu — APPROVED** [review]

**Review by 64991018 — APPROVED** [review]
LGTM

**Comment by iceeewrz** [comment]
2500 paycheck

**Comment by chatmethar-comp** [comment]
> add hello project

Hi

**Review by iceeewrz — APPROVED** [review]
2500 la bro

**Comment by PigaB00** [comment]
hello

**Pull request merged**
